/* ============================================================
   RÜYA — Speisekarte / Menü-Daten
   Bilingual DE / TR · Preise in € · 142 Positionen
   Allergene & Zusatzstoffe nennen wir gerne am Tisch.
   ============================================================ */

const CATS = [
  { id:"Vorspeisen", tr:"Başlangıç", tag:"Zum Ankommen — kleine Vorfreude" },
  { id:"Salate", tr:"Salata", tag:"Frisch, knackig, mit Liebe angerichtet" },
  { id:"Wraps", tr:"Sarma & Wrap", tag:"Mit Pommes & zwei Dips serviert" },
  { id:"Burger", tr:"Burger", tag:"Handgemacht, saftig, ehrlich" },
  { id:"Schnitzel", tr:"Şinitzel", tag:"Goldbraun paniert — Chef Arvens Klassiker" },
  { id:"Pizza", tr:"Pizza", tag:"Dünn, knusprig, aus dem Steinofen" },
  { id:"Pasta", tr:"Makarna", tag:"Cremig, würzig, hausgemacht" },
  { id:"Pfanne & Ofen", tr:"Tava & Fırın", tag:"Aus Pfanne und Ofen — herzhaft & überbacken" },
  { id:"Grill", tr:"Izgara", tag:"Vom Holzkohlegrill — Rauch & Glut" },
  { id:"Künefe", tr:"Künefe", tag:"Heiß serviert, frisch aus dem Ofen" },
  { id:"Desserts", tr:"Tatlılar", tag:"Süß wie ein Traum" },
  { id:"Heißgetränke", tr:"Sıcak İçecekler", tag:"Kaffeekultur & türkischer Çay" },
  { id:"Kalte Getränke", tr:"Soğuk İçecekler", tag:"Erfrischend & spritzig" },
  { id:"Waffeln & Eis", tr:"Waffle & Dondurma", tag:"Zum Naschen & Teilen" },
];

const MENU = [
  // — Vorspeisen —
  { nr:"01", c:"Vorspeisen", n:"Linsensuppe", t:"Mercimek Çorbası", d:"", p:"5,90" },
  { nr:"02", c:"Vorspeisen", n:"Pommes", t:"Patates Kızartması", d:"Pommes, 2 Dips nach Wahl", p:"5,90" },
  { nr:"03", c:"Vorspeisen", n:"Süßkartoffel-Pommes", t:"Tatlı Patates Kızartması", d:"Mit Sour Cream", p:"6,90" },
  { nr:"04", c:"Vorspeisen", n:"Vorspeisen-Mix", t:"Karışık Başlangıç", d:"Pommes, Kroketten, Chili-Cheese-Nuggets, Chicken-Nuggets, Mozzarella-Sticks", p:"9,90" },
  { nr:"05", c:"Vorspeisen", n:"Bruschetta", t:"", d:"Geröstete Brotscheiben, Tomaten, Olivenöl, Balsamico-Creme, Knoblauch", p:"10,90" },
  { nr:"06", c:"Vorspeisen", n:"Bruschetta Mozzarella", t:"", d:"Geröstetes Brot, Tomaten, Rucola, Zwiebeln, Knoblauch", p:"12,90" },
  { nr:"07", c:"Vorspeisen", n:"Bruschetta Garnelen", t:"Karidesli Bruschetta", d:"Tomaten, Zwiebeln, Knoblauch, Petersilie, Avocado, Garnelen", p:"12,90" },
  { nr:"08", c:"Vorspeisen", n:"Bruschetta Hähnchen", t:"Tavuklu Bruschetta", d:"Saisonale Blattsalate, Tomaten, Zwiebeln, paniertes Hähnchen", p:"13,90" },
  { nr:"09", c:"Vorspeisen", n:"Bruschetta Rosso", t:"", d:"Saisonale Blattsalate, Tomaten, Zwiebeln, Rinderfiletstreifen", p:"14,90" },
  { nr:"10", c:"Vorspeisen", n:"Rüya Hähnchen", t:"Rüya Tavuk", d:"Paniertes Hähnchen Julienne, Käsesoße, Pommes", p:"13,90" },
  // — Salate —
  { nr:"01", c:"Salate", n:"Hähnchen-Caesar-Salat", t:"Tavuklu Sezar Salatası", d:"Saisonsalat, Hähnchenbruststreifen, Parmesan, Cherrytomaten, Caesar-Dressing, Croutons", p:"14,90" },
  { nr:"02", c:"Salate", n:"Hähnchen-Avocado-Salat", t:"Tavuklu Avokado Salatası", d:"Saisonsalat, Hähnchenbruststreifen, Avocado, Olivenöl, Zitrone", p:"14,90" },
  { nr:"03", c:"Salate", n:"Hirtensalat", t:"Çoban Salatası", d:"Cherrytomaten, Gurken, Zwiebeln, Olivenöl, Zitrone", p:"9,90" },
  { nr:"04", c:"Salate", n:"Rüya Salat", t:"Rüya Salatası", d:"Saisonsalat, Cherrytomaten, Crispy Chicken, Joghurt-Dressing", p:"12,90" },
  { nr:"05", c:"Salate", n:"Griechischer Salat", t:"Yunan Salatası", d:"Saisonsalat, Cherrytomaten, Gurken, Zwiebeln, Feta, Olivenöl, Zitrone", p:"11,90" },
  { nr:"06", c:"Salate", n:"Lachs-Avocado-Salat", t:"Somon Avokado Salatası", d:"Saisonsalat, Lachs, Avocado, Olivenöl, Zitrone", p:"15,90" },
  { nr:"07", c:"Salate", n:"Thunfischsalat", t:"Ton Balığı Salatası", d:"Saisonsalat, Thunfisch, Zwiebeln, Mais, Olivenöl, Zitrone", p:"13,90" },
  // — Wraps —
  { nr:"01", c:"Wraps", n:"Brot Rullo", t:"Ekmek Rullo", d:"Hähnchen, Paprika, Zwiebeln, Knoblauch, Sahnesoße, Pommes", p:"14,90" },
  { nr:"02", c:"Wraps", n:"Chicken-Caesar-Wrap", t:"Tavuklu Sezar Wrap", d:"Weizentortilla, Eisbergsalat, Rucola, Hähnchenbrust, Croutons, Caesar-Dressing", p:"14,90" },
  { nr:"03", c:"Wraps", n:"Rüya-Wrap", t:"", d:"Weizentortilla, Eisbergsalat, Rucola, Crispy Chicken, Sweet-Chili-Soße", p:"14,90" },
  { nr:"04", c:"Wraps", n:"Geschnetzeltes Wrap", t:"Tantuni Wrap", d:"Weizentortilla, Kalbfleisch, Tomaten, Zwiebeln, Petersilie", p:"14,90" },
  { nr:"05", c:"Wraps", n:"Frikadellen-Wrap", t:"Köfte Wrap", d:"Weizentortilla, Frikadellen, Tomaten, Zwiebeln, Petersilie", p:"14,90" },
  { nr:"06", c:"Wraps", n:"Fajita-Hähnchen-Wrap", t:"Tavuk Fajita Wrap", d:"Weizentortilla, Fajita-Hähnchen, gebratene Paprika und Zwiebeln", p:"14,90" },
  { nr:"07", c:"Wraps", n:"Fajita-Rinder-Wrap", t:"Dana Fajita Wrap", d:"Weizentortilla, Fajita-Rind, gebratene Paprika und Zwiebeln", p:"15,90" },
  // — Burger —
  { nr:"01", c:"Burger", n:"Veggie Burger", t:"Vejetaryen Burger", d:"Veggie-Patty, Eisbergsalat, Tomaten, Zwiebeln, Burger-Soße", p:"13,90" },
  { nr:"02", c:"Burger", n:"Crispy Chicken Burger", t:"Krispi Tavuk Burger", d:"Crispy-Chicken-Patty, Eisbergsalat, Tomaten, Zwiebeln, Burger-Soße", p:"14,90" },
  { nr:"03", c:"Burger", n:"Hamburger", t:"", d:"Rinderpatty, Eisbergsalat, Tomaten, Zwiebeln, eingelegte Gurken, Burger-Soße", p:"14,90" },
  { nr:"04", c:"Burger", n:"Cheeseburger", t:"", d:"Rinderpatty, Eisbergsalat, Tomaten, Zwiebeln, Gurken, Cheddar, Burger-Soße", p:"15,90" },
  { nr:"05", c:"Burger", n:"Caprese Burger", t:"", d:"Hähnchenbrust, Mozzarella, Tomaten, Zwiebeln, Basilikum, Basilikum-Soße", p:"15,90" },
  { nr:"06", c:"Burger", n:"Chili-Cheese-Burger", t:"", d:"Rinderpatty, Cheddar, Jalapeños, Chili-Cheese-Soße", p:"16,50" },
  { nr:"07", c:"Burger", n:"Rüya Burger", t:"", d:"Rinderpatty, doppeltes Rinderfilet, Cheddar, Burger-Soße", p:"20,90" },
  // — Schnitzel —
  { nr:"01", c:"Schnitzel", n:"Hähnchenschnitzel Wiener Art", t:"Viyana Usulü Şinitzel", d:"Paniertes Hähnchen", p:"12,90" },
  { nr:"02", c:"Schnitzel", n:"Chef Arvens Mediterranes Schnitzel", t:"", d:"Brokkoli, Champignons, Zwiebeln, Knoblauch, Tomatensoße", p:"17,90" },
  { nr:"03", c:"Schnitzel", n:"Rüya Schnitzel", t:"", d:"Paniertes Hähnchen, Spinat, Knoblauch, Champignons, Sahnesoße", p:"17,90" },
  { nr:"04", c:"Schnitzel", n:"Jägerschnitzel", t:"Avcı Şinitzel", d:"Paniertes Hähnchen, Champignons, Sahnesoße", p:"17,90" },
  { nr:"05", c:"Schnitzel", n:"Spinat-Schnitzel", t:"Ispanaklı Şinitzel", d:"Paniertes Hähnchen, Spinat, Knoblauch, Sahnesoße", p:"17,90" },
  { nr:"06", c:"Schnitzel", n:"Broccoli-Schnitzel", t:"Brokolili Şinitzel", d:"Paniertes Hähnchen, Brokkoli, Sahnesoße", p:"17,90" },
  { nr:"07", c:"Schnitzel", n:"Blumenkohl-Schnitzel", t:"Karnıbahar Şinitzel", d:"Paniertes Hähnchen, Blumenkohl, Hollandaise-Soße", p:"17,90" },
  { nr:"08", c:"Schnitzel", n:"Spargel-Schnitzel", t:"Kuşkonmaz Şinitzel", d:"Paniertes Hähnchen, Spargel, Hollandaise-Soße", p:"17,90" },
  { nr:"09", c:"Schnitzel", n:"Schnitzel mit Rahmsoße", t:"Kremalı Soslu Şinitzel", d:"Paniertes Hähnchen, Rahmsoße", p:"17,90" },
  { nr:"10", c:"Schnitzel", n:"Schnitzel mit Hollandaise", t:"Hollandaise Soslu Şinitzel", d:"Paniertes Hähnchen, Hollandaise-Soße", p:"17,90" },
  { nr:"11", c:"Schnitzel", n:"Schnitzel Balkan Art", t:"Balkan Tarzı Şinitzel", d:"Paniertes Hähnchen, Balkan-Soße mit Paprika und Zwiebel", p:"17,90" },
  { nr:"12", c:"Schnitzel", n:"Hawaii-Schnitzel", t:"Hawaii Şinitzel", d:"Paniertes Hähnchen, Ananas, Sahnesoße", p:"17,90" },
  // — Pizza —
  { nr:"01", c:"Pizza", n:"Pizza Margherita", t:"", d:"Tomatensoße, Mozzarella", p:"9,90" },
  { nr:"02", c:"Pizza", n:"Pizza Quattro Formaggi", t:"", d:"Gorgonzola, Parmesan, Feta, Mozzarella", p:"13,90" },
  { nr:"03", c:"Pizza", n:"Pizza Veggie", t:"Vejetaryen", d:"Spinat, Champignons, Brokkoli, Zwiebeln, Paprika, Cherrytomaten", p:"13,90" },
  { nr:"04", c:"Pizza", n:"Pizza Knoblauchwurst", t:"Sucuklu Pizza", d:"Türkische Knoblauchwurst", p:"13,90" },
  { nr:"05", c:"Pizza", n:"Pizza Tonno", t:"Ton Balıklı Pizza", d:"Thunfisch, Zwiebeln", p:"13,90" },
  { nr:"06", c:"Pizza", n:"Pizza Caprese", t:"", d:"Mozzarella, Cherrytomaten, Basilikum", p:"13,90" },
  { nr:"07", c:"Pizza", n:"Pizza Lachs-Spinat", t:"Somon Ispanaklı Pizza", d:"Lachs, Spinat, Knoblauch", p:"13,90" },
  { nr:"08", c:"Pizza", n:"Pizza Rucola", t:"Rokalı Pizza", d:"Rucola, Cherrytomaten, Parmesan, Olivenöl", p:"13,90" },
  { nr:"09", c:"Pizza", n:"Pizza Rüya", t:"", d:"Türkische Knoblauchwurst, türkischer Speck, Paprika, Jalapeños", p:"14,90" },
  { nr:"10", c:"Pizza", n:"Pizza Hollandaise", t:"Hollandez Pizza", d:"Hollandaise-Soße, Hähnchen, Brokkoli, Jalapeños", p:"14,90" },
  // — Pasta —
  { nr:"01", c:"Pasta", n:"Pasta Napoli", t:"", d:"Tomatensoße", p:"11,90" },
  { nr:"02", c:"Pasta", n:"Pasta Arrabbiata", t:"", d:"Chili, Tomaten, Basilikum", p:"13,90" },
  { nr:"03", c:"Pasta", n:"Pasta Bolognese", t:"", d:"Hackfleisch, Tomatensoße", p:"13,90" },
  { nr:"04", c:"Pasta", n:"Pasta Alfredo", t:"", d:"Käse-Sahne-Soße, Parmesan", p:"13,90" },
  { nr:"05", c:"Pasta", n:"Pasta Aglio e Olio", t:"", d:"Olivenöl, Knoblauch, Cherrytomaten, Petersilie", p:"13,90" },
  { nr:"06", c:"Pasta", n:"Pasta Veggie", t:"Vejetaryen", d:"Brokkoli, Champignons, Paprika, Zwiebeln, Knoblauch, Karotten, Tomaten-Sahne-Soße", p:"13,90" },
  { nr:"07", c:"Pasta", n:"Türkische Tortellini", t:"Mantı", d:"Türkische Tortellini, Joghurt, Tomatenmark, Minze", p:"13,90" },
  { nr:"08", c:"Pasta", n:"Pasta Spinat", t:"Ispanaklı Makarna", d:"Sahnesoße, Spinat, Knoblauch", p:"14,90" },
  { nr:"09", c:"Pasta", n:"Pasta Garnelen", t:"Karidesli Makarna", d:"Tomaten-Sahne-Soße, Garnelen, Knoblauch, Petersilie, Zwiebeln", p:"14,90" },
  { nr:"10", c:"Pasta", n:"Pasta Brokkoli Alfredo", t:"", d:"Hähnchenbrust, Käse-Sahne-Soße, Brokkoli", p:"14,90" },
  { nr:"11", c:"Pasta", n:"Pasta Chicken Champignon", t:"Tavuklu Mantarlı Makarna", d:"Hähnchenbrust, Champignons, Parmesan-Sahne-Soße", p:"14,90" },
  { nr:"12", c:"Pasta", n:"Pasta Chicken Curry", t:"Tavuk Köri Makarna", d:"Hähnchenbrust, Curry-Sahne-Soße", p:"14,90" },
  { nr:"13", c:"Pasta", n:"Chef Pasta", t:"", d:"Crispy Chicken, Spinat, Champignons, Zwiebeln, Knoblauch, Sahnesoße", p:"15,90" },
  { nr:"14", c:"Pasta", n:"Pasta Pesto", t:"", d:"Hähnchenbrust, Cherrytomaten, Pesto-Sahne-Soße, Basilikum", p:"15,90" },
  { nr:"15", c:"Pasta", n:"Chef's Lachs", t:"Şefin Somonu", d:"Lachs, Champignons, Zwiebeln, Knoblauch, Spinat, Sahnesoße", p:"17,90" },
  // — Pfanne & Ofen —
  { nr:"01", c:"Pfanne & Ofen", n:"Chef's Beef", t:"Şefin Bonfilesi", d:"Rinderfilet Julienne, Zwiebeln, Knoblauch, Cherrytomaten, Joghurt, Croutons", p:"24,90" },
  { nr:"02", c:"Pfanne & Ofen", n:"Chef Spezial", t:"Şef Spezyal", d:"Rindfleischstreifen, Champignons, Demi-Glace-Soße, Kartoffelpüree, Salat", p:"27,90" },
  { nr:"03", c:"Pfanne & Ofen", n:"Rüya Spezial", t:"", d:"Hähnchenbrust, Champignons, Rahmsoße, Kartoffelpüree, Salat", p:"19,90" },
  { nr:"04", c:"Pfanne & Ofen", n:"Spezial Hähnchen", t:"Spezyal Tavuk", d:"Hähnchenbrust, Spinat, Sahnesoße, Parmesan, Pommes oder Reis", p:"21,90" },
  { nr:"05", c:"Pfanne & Ofen", n:"Hähnchen mit Champignonsoße", t:"Mantar Soslu Tavuk", d:"Hähnchenbrust, Champignon-Sahne-Soße, Pommes oder Reis, Salat", p:"18,90" },
  { nr:"06", c:"Pfanne & Ofen", n:"Hähnchenbrust", t:"Tavuk Göğsü", d:"Hähnchenbrust, Pommes oder Reis, Salat", p:"16,90" },
  { nr:"07", c:"Pfanne & Ofen", n:"Chicken Teriyaki", t:"Tavuk Teriyaki", d:"Hähnchen, Sojasoße, Honig, Ingwer, Knoblauch, Sesam, Reis", p:"18,90" },
  { nr:"08", c:"Pfanne & Ofen", n:"Pilz-Curry-Hähnchen", t:"Mantarlı Köri Tavuk", d:"Champignons, Currysoße, Hähnchenbrust, Reis, Pommes", p:"18,90" },
  { nr:"09", c:"Pfanne & Ofen", n:"Chef Arven Signature Dish", t:"", d:"Hähnchen Julienne, Paprika, Zwiebeln, Champignons, Knoblauch, Tomaten, Sahnesoße — überbacken", p:"19,90" },
  { nr:"10", c:"Pfanne & Ofen", n:"Chef Mediterranée Arven", t:"", d:"Rinderfilet, Champignons, Zwiebeln, Knoblauch, Tomaten-Sahne-Soße — überbacken", p:"26,90" },
  { nr:"11", c:"Pfanne & Ofen", n:"Chef Arvens BBQ Hähnchen", t:"Şefin BBQ Tavuğu", d:"Hähnchen, Paprika, Chili, Salsa, Sour Cream, Guacamole, Tortilla", p:"19,90" },
  { nr:"12", c:"Pfanne & Ofen", n:"Chef Arvens BBQ Rind", t:"Şefin BBQ Bonfilesi", d:"Rindfleisch, Paprika, Chili, Salsa, Sour Cream, Guacamole, Tortilla", p:"22,90" },
  { nr:"13", c:"Pfanne & Ofen", n:"Beef Stroganoff", t:"", d:"Rinderfilet Julienne, Champignons, Sahnesoße, Reis, Salat, eingelegte Gurken", p:"26,90" },
  { nr:"14", c:"Pfanne & Ofen", n:"Rinderpfanne", t:"Saç Kavurma", d:"Rindfleisch, Tomaten, Zwiebeln, Knoblauch, grüne Paprika, Pommes, Reis", p:"22,90" },
  { nr:"15", c:"Pfanne & Ofen", n:"Hähnchenpfanne", t:"Saç Kavurma Tavuk", d:"Hähnchen, Tomaten, Zwiebeln, Knoblauch, grüne Paprika, Pommes, Reis", p:"18,90" },
  { nr:"16", c:"Pfanne & Ofen", n:"Garnelenpfanne", t:"Karides Tava", d:"Garnelen, Butter, Knoblauch, Pommes", p:"23,90" },
  { nr:"17", c:"Pfanne & Ofen", n:"Garnelen-Schmortopf", t:"Karides Güveç", d:"Garnelen, Butter, Champignons, Baby-Kartoffeln, Zwiebeln, Knoblauch", p:"19,90" },
  { nr:"18", c:"Pfanne & Ofen", n:"Rüya-Schmortopf", t:"Rüya Güveç", d:"Frikadellen, Tomatensoße, Paprika, Gouda", p:"19,90" },
  // — Grill —
  { nr:"01", c:"Grill", n:"Adana", t:"", d:"Lamm-Hackfleischspieß, Pommes oder Reis, Salat", p:"18,90" },
  { nr:"02", c:"Grill", n:"Lammspieß", t:"Kuzu Şiş", d:"Lammspieß, Pommes oder Reis, Salat", p:"19,90" },
  { nr:"03", c:"Grill", n:"Hähnchenspieß", t:"Tavuk Şiş", d:"Mariniertes Hähnchen, Pommes oder Reis, Salat", p:"18,90" },
  { nr:"04", c:"Grill", n:"Gegrillte Frikadelle", t:"Izgara Köfte", d:"Gegrillte Frikadellen, Salat, Pommes oder Reis", p:"18,90" },
  { nr:"05", c:"Grill", n:"Lammkoteletts", t:"Kuzu Pirzola", d:"Lammkoteletts, Pommes oder Reis, Salat", p:"22,90" },
  { nr:"06", c:"Grill", n:"Rüya Grillteller", t:"Rüya Karışık", d:"Hähnchenspieß, Lammspieß, Kotelett, Adana, Frikadellen, Pommes oder Reis, Salat", p:"26,90" },
  { nr:"07", c:"Grill", n:"Chef Arvens Surf & Turf", t:"", d:"Rinderfiletstreifen, Garnelen, Tagliatelle, Dill-Knoblauch-Sahne-Soße", p:"34,90" },
  { nr:"08", c:"Grill", n:"Gegrillter Lachs", t:"Izgara Somon", d:"Gegrillter Lachs, Dillsoße, Rosmarinkartoffeln, Salat", p:"22,90" },
  // — Desserts —
  { nr:"01", c:"Desserts", n:"San Sebastian Cheesecake", t:"", d:"", p:"6,90" },
  { nr:"02", c:"Desserts", n:"Dubai Cheesecake", t:"Bardak / Pasta — im Glas oder als Kuchen", d:"", p:"6,90" },
  { nr:"03", c:"Desserts", n:"Bueno Cheesecake", t:"Bardak / Pasta — im Glas oder als Kuchen", d:"", p:"6,90" },
  { nr:"04", c:"Desserts", n:"Pistazien Cheesecake", t:"Fıstıklı Cheesecake Bardak", d:"", p:"6,90" },
  { nr:"05", c:"Desserts", n:"Lotus Cheesecake", t:"", d:"", p:"6,90" },
  { nr:"06", c:"Desserts", n:"Dubai Bombe", t:"Dubai Bombası", d:"", p:"6,90" },
  { nr:"07", c:"Desserts", n:"Dubai Tiramisu", t:"", d:"Großes Format — zum Teilen", p:"18,90" },
  { nr:"08", c:"Desserts", n:"Dubai Schokolade", t:"Dubai Çikolata", d:"", p:"7,90" },
  { nr:"09", c:"Desserts", n:"Dubai Herz", t:"Dubai Kalp", d:"", p:"5,90" },
  { nr:"10", c:"Desserts", n:"Tiramisu", t:"", d:"", p:"5,90" },
  { nr:"11", c:"Desserts", n:"Magnolia Erdbeere", t:"Çilekli Magnolia", d:"Auch mit Oreo", p:"6,90" },
  { nr:"12", c:"Desserts", n:"Brownie", t:"", d:"", p:"5,90" },
  { nr:"13", c:"Desserts", n:"Trilice", t:"Trileçe", d:"", p:"5,90" },
  { nr:"14", c:"Desserts", n:"Milchreis", t:"Sütlaç", d:"", p:"4,90" },
  { nr:"15", c:"Desserts", n:"Cédric-Grolet-Frucht Apfel", t:"Elma", d:"", p:"5,90" },
  { nr:"16", c:"Desserts", n:"Cédric-Grolet-Frucht Himbeere", t:"Ahududu", d:"", p:"5,90" },
  { nr:"17", c:"Desserts", n:"Cédric-Grolet-Frucht Mango", t:"", d:"", p:"5,90" },
  { nr:"18", c:"Desserts", n:"Cédric-Grolet-Frucht Pistazie", t:"Antep Fıstığı", d:"", p:"8,90" },
  { nr:"19", c:"Desserts", n:"Cédric-Grolet-Frucht Zitrone", t:"Limon", d:"", p:"5,90" },
  // — Künefe —
  { nr:"01", c:"Künefe", n:"Künefe Pistazie", t:"Fıstıklı Künefe", d:"", p:"8,90" },
  { nr:"02", c:"Künefe", n:"Künefe mit Eis", t:"Dondurmalı Künefe", d:"", p:"9,90" },
  { nr:"03", c:"Künefe", n:"Künefe mit Mascarpone", t:"Mascarponeli Künefe", d:"", p:"9,90" },
  { nr:"04", c:"Künefe", n:"Künefe mit Bueno-Soße", t:"Bueno Soslu Künefe", d:"", p:"9,90" },
  { nr:"05", c:"Künefe", n:"Rüya Künefe", t:"Meyveli Nutella-Bueno Soslu", d:"Mit Früchten & Nutella-Bueno-Soße", p:"14,90" },
  // — Waffeln & Eis —
  { nr:"01", c:"Waffeln & Eis", n:"Waffel mit Puderzucker & Sahne", t:"Pudra şekerli & kremalı waffle", d:"", p:"5,90" },
  { nr:"02", c:"Waffeln & Eis", n:"Waffel mit Nutella & Vanilleeis", t:"Nutella & vanilyalı dondurmalı waffle", d:"", p:"6,90" },
  { nr:"03", c:"Waffeln & Eis", n:"Waffel Nutella, Erdbeeren & Vanilleeis", t:"", d:"", p:"7,90" },
  { nr:"04", c:"Waffeln & Eis", n:"Waffel mit heißen Kirschen & Vanilleeis", t:"Sıcak vişneli waffle", d:"", p:"7,90" },
  { nr:"05", c:"Waffeln & Eis", n:"Waffel Nutella, Früchte & Vanilleeis", t:"", d:"", p:"8,90" },
  { nr:"06", c:"Waffeln & Eis", n:"Waffel Lotussoße, Banane & Vanilleeis", t:"", d:"", p:"7,90" },
  { nr:"07", c:"Waffeln & Eis", n:"Waffel Nutella, Erdbeere, Oreo & Erdbeereis", t:"", d:"", p:"7,90" },
  { nr:"08", c:"Waffeln & Eis", n:"Eis pro Kugel", t:"Dondurma — Top", d:"Vanille, Schoko, Erdbeere, Haselnuss, Stracciatella, Amarena, Cookie, Zitrone, Joghurt u. m.", p:"2,00" },
  // — Heißgetränke —
  { nr:"01", c:"Heißgetränke", n:"Espresso", t:"", d:"", p:"2,90" },
  { nr:"02", c:"Heißgetränke", n:"Cappuccino", t:"", d:"", p:"3,50" },
  { nr:"03", c:"Heißgetränke", n:"Latte Macchiato", t:"Auch Karamell, Vanille, Kokos, Schoko +0,20", d:"", p:"3,70" },
  { nr:"04", c:"Heißgetränke", n:"Kaffee Schwarz", t:"", d:"", p:"3,30" },
  { nr:"05", c:"Heißgetränke", n:"Türkischer Mokka", t:"Türk Kahvesi", d:"", p:"3,90" },
  { nr:"06", c:"Heißgetränke", n:"Çay", t:"Türkischer Tee — klein 1,50 / groß 2,00", d:"", p:"1,50" },
  { nr:"07", c:"Heißgetränke", n:"Heiße Schokolade", t:"", d:"", p:"3,50" },
  { nr:"08", c:"Heißgetränke", n:"Frischer Pfefferminztee", t:"Mit Honig und Zitrone", d:"", p:"3,90" },
  // — Kalte Getränke —
  { nr:"01", c:"Kalte Getränke", n:"Ice Tea", t:"Peach, Lemon, Cherry, Blueberry, Pomegranate u. m. — 0,33 l", d:"", p:"3,40" },
  { nr:"02", c:"Kalte Getränke", n:"Fritz Limonaden", t:"Cola, Zitrone, Orange, HonigMelone u. m. — 0,3 l", d:"", p:"3,30" },
  { nr:"03", c:"Kalte Getränke", n:"Softdrinks", t:"Cola, Sprite, Fanta, Mezzo Mix — 0,33 l", d:"", p:"3,30" },
  { nr:"04", c:"Kalte Getränke", n:"Red Bull", t:"0,25 l", d:"", p:"3,40" },
  { nr:"05", c:"Kalte Getränke", n:"Trinkgenuss Säfte", t:"Pfirsich, Multi, Orange, Apfel — 0,2 l", d:"", p:"2,90" },
  { nr:"06", c:"Kalte Getränke", n:"Schorle Maracuja", t:"0,3 l", d:"", p:"3,30" },
  { nr:"07", c:"Kalte Getränke", n:"Uludağ Gazoz", t:"0,31 l", d:"", p:"2,90" },
  { nr:"08", c:"Kalte Getränke", n:"Wasser", t:"Apollinaris / Vio — 0,25 l", d:"", p:"2,90" },
];

// German allergen + additive legend (Kennzeichnung)
const LEGEND = [
  { k:"G", v:"Gluten" },
  { k:"E", v:"Ei" },
  { k:"M", v:"Milch / Laktose" },
  { k:"F", v:"Fisch" },
  { k:"K", v:"Krebstiere" },
  { k:"SF", v:"Schalenfrüchte / Nüsse" },
  { k:"So", v:"Soja" },
  { k:"Se", v:"Sesam" },
  { k:"3", v:"Antioxidationsmittel" },
  { k:"6", v:"geschwärzt" },
  { k:"9", v:"koffeinhaltig" },
  { k:"10", v:"chininhaltig" },
];

if (typeof module !== 'undefined') { module.exports = { MENU, CATS, LEGEND }; }
